export const companyNameAndEmail = [
  { companyName: "BlogXS", companyEmail: "sregan0@mapy.cz" },
  { companyName: "Realcube", companyEmail: "drandales1@e-recht24.de" },
  { companyName: "Thoughtbeat", companyEmail: "mfetters2@ow.ly" },
  { companyName: "Meedoo", companyEmail: "hwillford3@delicious.com" },
  { companyName: "Babbleset", companyEmail: "hbealing4@addtoany.com" },
  { companyName: "Edgeclub", companyEmail: "mhayller5@hostgator.com" },
  { companyName: "Buzzdog", companyEmail: "rcogley6@marketwatch.com" },
  { companyName: "Gabtype", companyEmail: "rmacbrearty7@ebay.com" },
  { companyName: "Flipopia", companyEmail: "wredding8@csmonitor.com" },
  { companyName: "Trudoo", companyEmail: "dwoolfitt9@jiathis.com" },
  { companyName: "Topiclounge", companyEmail: "croalfea@seattletimes.com" },
  { companyName: "Oyonder", companyEmail: "tabramzonb@ca.gov" },
  { companyName: "Buzzdog", companyEmail: "cpimblottc@ifeng.com" },
  { companyName: "Dynazzy", companyEmail: "mmcglued@indiegogo.com" },
  { companyName: "Oozz", companyEmail: "dkohrse@slate.com" },
  { companyName: "Tagpad", companyEmail: "upalfremanf@webs.com" },
  { companyName: "Twitternation", companyEmail: "omcnamarag@webmd.com" },
  { companyName: "Avaveo", companyEmail: "lodoghertyh@g.co" },
  { companyName: "Centidel", companyEmail: "ushillabeeri@shinystat.com" },
  { companyName: "Oyoba", companyEmail: "pcreavinj@instagram.com" },
];
