const data = [
  {
    userId: "64b0c0bbfc13ae2768beec56",
    companyName: "BlogXS",
    payment: 5437204,
    companyEmail: "sregan0@mapy.cz",
  },
  {
    userId: "64b0c0bbfc13ae2768beec57",
    companyName: "Realcube",
    payment: 5461913,
    companyEmail: "drandales1@e-recht24.de",
  },
  {
    userId: "64b0c0bbfc13ae2768beec58",
    companyName: "Thoughtbeat",
    payment: 8591359,
    companyEmail: "mfetters2@ow.ly",
  },
  {
    userId: "64b0c0bbfc13ae2768beec59",
    companyName: "Meedoo",
    payment: 182740,
    companyEmail: "hwillford3@delicious.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec5a",
    companyName: "Babbleset",
    payment: 3640450,
    companyEmail: "hbealing4@addtoany.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec5b",
    companyName: "Edgeclub",
    payment: 5072163,
    companyEmail: "mhayller5@hostgator.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec5c",
    companyName: "Buzzdog",
    payment: 1755805,
    companyEmail: "rcogley6@marketwatch.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec5d",
    companyName: "Gabtype",
    payment: 6361666,
    companyEmail: "rmacbrearty7@ebay.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec5e",
    companyName: "Flipopia",
    payment: 2469602,
    companyEmail: "wredding8@csmonitor.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec5f",
    companyName: "Trudoo",
    payment: 9483239,
    companyEmail: "dwoolfitt9@jiathis.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec60",
    companyName: "Topiclounge",
    payment: 3887502,
    companyEmail: "croalfea@seattletimes.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec61",
    companyName: "Oyonder",
    payment: 2465490,
    companyEmail: "tabramzonb@ca.gov",
  },
  {
    userId: "64b0c0bbfc13ae2768beec62",
    companyName: "Buzzdog",
    payment: 7891937,
    companyEmail: "cpimblottc@ifeng.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec63",
    companyName: "Dynazzy",
    payment: 8067703,
    companyEmail: "mmcglued@indiegogo.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec64",
    companyName: "Oozz",
    payment: 2851569,
    companyEmail: "dkohrse@slate.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec65",
    companyName: "Tagpad",
    payment: 899174,
    companyEmail: "upalfremanf@webs.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec66",
    companyName: "Twitternation",
    payment: 3929906,
    companyEmail: "omcnamarag@webmd.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec67",
    companyName: "Avaveo",
    payment: 5485012,
    companyEmail: "lodoghertyh@g.co",
  },
  {
    userId: "64b0c0bbfc13ae2768beec68",
    companyName: "Centidel",
    payment: 2408059,
    companyEmail: "ushillabeeri@shinystat.com",
  },
  {
    userId: "64b0c0bbfc13ae2768beec69",
    companyName: "Oyoba",
    payment: 3945561,
    companyEmail: "pcreavinj@instagram.com",
  },
];

export const companyNameAndEmail = [
  { companyName: "BlogXS", companyEmail: "sregan0@mapy.cz" },
  { companyName: "Realcube", companyEmail: "drandales1@e-recht24.de" },
  { companyName: "Thoughtbeat", companyEmail: "mfetters2@ow.ly" },
  { companyName: "Meedoo", companyEmail: "hwillford3@delicious.com" },
  { companyName: "Babbleset", companyEmail: "hbealing4@addtoany.com" },
  { companyName: "Edgeclub", companyEmail: "mhayller5@hostgator.com" },
  { companyName: "Buzzdog", companyEmail: "rcogley6@marketwatch.com" },
  { companyName: "Gabtype", companyEmail: "rmacbrearty7@ebay.com" },
  { companyName: "Flipopia", companyEmail: "wredding8@csmonitor.com" },
  { companyName: "Trudoo", companyEmail: "dwoolfitt9@jiathis.com" },
  { companyName: "Topiclounge", companyEmail: "croalfea@seattletimes.com" },
  { companyName: "Oyonder", companyEmail: "tabramzonb@ca.gov" },
  { companyName: "Buzzdog", companyEmail: "cpimblottc@ifeng.com" },
  { companyName: "Dynazzy", companyEmail: "mmcglued@indiegogo.com" },
  { companyName: "Oozz", companyEmail: "dkohrse@slate.com" },
  { companyName: "Tagpad", companyEmail: "upalfremanf@webs.com" },
  { companyName: "Twitternation", companyEmail: "omcnamarag@webmd.com" },
  { companyName: "Avaveo", companyEmail: "lodoghertyh@g.co" },
  { companyName: "Centidel", companyEmail: "ushillabeeri@shinystat.com" },
  { companyName: "Oyoba", companyEmail: "pcreavinj@instagram.com" },
];

export default data;
